name: Check

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Test
        run: |
          xcodebuild test \
            -project wled.xcodeproj \
            -scheme wled \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

  lint:
    name: Run Lint
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint lint --reporter github-actions-logging
